name: flutter_multi_screenshot
description: "A Flutter plugin for capturing screenshots on Linux."
version: 1.0.2
homepage: https://github.com/DavidMtundi/multi_screenshot_capture
repository: https://github.com/DavidMtundi/multi_screenshot_capture

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterMultiScreenshotPlugin
